export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCT_BY_ID_REQUEST";
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS";
export const FIND_PRODUCT_BY_ID_FAILURE = "FIND_PRODUCT_BY_ID_FAILURE";

export const FIND_PRODUCT_BY_TITLE_REQUEST = "FIND_PRODUCT_BY_TITLE_REQUEST";
export const FIND_PRODUCT_BY_TITLE_SUCCESS = "FIND_PRODUCT_BY_TITLE_SUCCESS";
export const FIND_PRODUCT_BY_TITLE_FAILURE = "FIND_PRODUCT_BY_TITLE_FAILURE";

export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCTS_REQUEST";
export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCTS_SUCCESS";
export const FIND_PRODUCTS_FAILURE = "FIND_PRODUCTS_FAILURE";

export const FIND_ALL_PRODUCT_REQUEST = "FIND_ALL_PRODUCT_REQUEST";
export const FIND_ALL_PRODUCT_SUCCESS = "FIND_ALL_PRODUCT_SUCCESS";
export const FIND_ALL_PRODUCT_FAILURE = "FIND_ALL_PRODUCT_FAILURE";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
